### ISSUE TITLE
Unable to build (package not found for windows_amd64)

### ISSUE THREAD

**Issue by naamah75** [TheRealWaldo/esp8266-amg8833#4]
I'm trying to build the project that I've already done in the past, but now I'm get the following error:

`Error: Could not find the package with 'TheRealWaldo/SparkFun GridEYE AMG88 Library @ ^1.0.2' requirements for your system 'windows_amd64'`

Maybe some updated library bring the problem?

PIO version: Core 6.1.5a4 - Home 3.4.3

**Comment by TheRealWaldo** [comment]
Libraries haven't changed.  What commands are you running to build?

**Comment by naamah75** [comment]
*  Esecuzione dell'attività: C:\Users\webma\.platformio\penv\Scripts\platformio.exe run --environment d1_mini 

Processing d1_mini (platform: espressif8266; board: d1_mini; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing TheRealWaldo/SparkFun GridEYE AMG88 Library @ ^1.0.2
Error: Could not find the package with 'TheRealWaldo/SparkFun GridEYE AMG88 Library @ ^1.0.2' requirements for your system 'windows_amd64'

 *  Il processo del terminale "C:\Users\webma\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'd1_mini'" è stato terminato. Codice di uscita: 1.

**Comment by TheRealWaldo** [comment]
I'm not sure why it would be trying to pull a package for the windows system.  I would guess there is a configuration error somewhere in your IDE.  Nothing has changed in these packages for 16 months, and it is still building in my environment.

I suggest you manually pull the package into your folder if you cannot identify the configuration issue.

https://github.com/TheRealWaldo/SparkFun_GridEYE_Arduino_Library

**Comment by naamah75** [comment]
I tried with another PC that I had used in the past to build the project but I get the same error.
I deleted the project and cloned the source from github, but nothing to do same problem.

**Comment by TheRealWaldo** [comment]
@naamah75 I've pushed a version that may resolve your issue; it seems the internals of platform.io may have changed concerning fetching libraries.  Two libraries stopped pulling even on my main development machine.

In addition to the build succeeding, I updated two libraries to the latest available versions.

Please let me know if you still see issues.
